name: gallos_app
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  pdf: ^3.10.4
  google_fonts: ^4.0.4
  path_provider: ^2.1.2
  open_file: ^3.3.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  # Actualización a la versión más reciente de flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - assets/bienvenida.png

flutter_icons:
  android: true  # Generar icono para Android
  ios: true      # Generar icono para iOS
  image_path: "assets/icono_app.png"  # Ruta a tu icono personalizado
